expense_uploader/urls.py
from django.conf.urls import url

from . import views


app_name = 'e_up'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload/$', views.upload, name='upload'),
]

waveSEchallenge/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^index/', include('expense_uploader.urls')),
    url(r'^admin/', admin.site.urls),
]

expense_uploader/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class File(models.Model):
    upload_date = models.DateTimeField(auto_now_add=True)
    #user_id
    #primary key autogenerated
    filename = models.CharField(max_length=100)
    raw = models.FileField(upload_to='uploads/%Y/%m/%d/')

class Expense(models.Model):
    date = models.DateField()
    category = models.CharField(max_length=100) # it might make more sense to make this column an enum
    employee_name = models.CharField(max_length=100)
    employee_address = models.CharField(max_length=100)
    expense_description = models.CharField(max_length=100)
    pre_tax_amount = models.DecimalField(max_digits=8, decimal_places=2)
    tax_name = models.CharField(max_length=100)
    tax_amount = models.DecimalField(max_digits=8, decimal_places=2)
    file = models.ForeignKey(File, on_delete=models.CASCADE)

expense_uploader/forms.py
from django import forms

class UploadForm(forms.Form):
    csv_file = forms.FileField(label='Select CSV File',widget=forms.FileInput(attrs={
        'name': 'csv_file',
        'id': 'csv_file',
        'type':'file',
        'style':'display:none;'
    }))

expense_uploader/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import File, Expense
import csv
from django.db import transaction
from .forms import UploadForm
import datetime
# Create your views here.

from django.http import HttpResponse


def index(request):
    expense_query = Expense.objects.all()
    context = {'expense_query' : expense_query}

    form = UploadForm()
    context['form'] = form

    return render(request, "expense_uploader/index.html", context)

# handles file upload and storage in database
def upload(request):
    f = request.FILES['csv_file']
    filedata = File(filename = f.name, raw = f)
    filedata.save()
    reader = csv.DictReader(f, delimiter = ',')
    with transaction.atomic():
        for row in reader:
            pre_tax_f = format_money_string(row['pre-tax amount'])
            tax_f = format_money_string(row['tax amount'])
            date_f = format_date_string(row['date'])
            record = Expense(
                date = date_f,
                category = row['category'],
                employee_name = row['employee name'],
                employee_address = row['employee address'],
                expense_description = row['expense description'],
                pre_tax_amount = pre_tax_f,
                tax_name = row['tax name'],
                tax_amount = tax_f,
                file = filedata
            )
            record.save()

            print(row['date'])

    return HttpResponseRedirect(reverse('e_up:index'))

# helper functions
def format_money_string(moneystring):
    s = moneystring.translate(None, ' ,$')
    return float(s)

def format_date_string(datestring):
    return datetime.datetime.strptime(datestring, '%m/%d/%Y')

expense_uploader/templates/expense_uploader/index.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}
<script src="{% static 'expense_uploader/some_js.js' %}"></script>

<div id="top-padding" style="width:100%;height:50px"></div>

<div class="container">
    <form action="{% url 'e_up:upload' %}" method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {% bootstrap_form form layout='' label_class='select_file btn btn-default btn-file btn-lg btn-block'%}
        {% buttons %}
            <button type="submit" class="btn btn-primary btn-lg btn-block">
                {% bootstrap_icon "upload" %} Upload
            </button>
        {% endbuttons %}
    </form>
</div>

<div class="container">
    <table class="table table-hover">
    <thead>
    <tr>
        <th>Date</th>
        <th>Category</th>
        <th>Employee</th>
        <th>Address</th>
        <th>Expense</th>
        <th>Pre-Tax Amount</th>
        <th>Tax Name</th>
        <th>Tax Amount</th>
    </tr>
    </thead>
    <tbody>
    {% if expense_query %}
        {% for expense in expense_query %}
            <tr>
                <td>{{ expense.date }}</td>
                <td>{{ expense.category }}</td>
                <td>{{ expense.employee_name }}</td>
                <td>{{ expense.employee_address }}</td>
                <td>{{ expense.expense_description }}</td>
                <td>{{ expense.pre_tax_amount }}</td>
                <td>{{ expense.tax_name }}</td>
                <td>{{ expense.tax_amount }}</td>
            </tr>
        {% endfor %}
    {% else %}
        <p>Database Empty</p>
    {% endif %}
    </tbody>
    </table>
</div>